<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub/protoc/pubsub.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Identity</code>
 */
class Identity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string clientId = 1;</code>
     */
    private $clientId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $clientId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pubsub\Protoc\Pubsub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string clientId = 1;</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->clientId;
    }

    /**
     * Generated from protobuf field <code>string clientId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientId = $var;

        return $this;
    }

}

