<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub/protoc/pubsub.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PublishRequest</code>
 */
class PublishRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Subscription topic = 1;</code>
     */
    private $topic = null;
    /**
     * Generated from protobuf field <code>repeated .Message messages = 2;</code>
     */
    private $messages;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Subscription $topic
     *     @type \Message[]|\Google\Protobuf\Internal\RepeatedField $messages
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pubsub\Protoc\Pubsub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Subscription topic = 1;</code>
     * @return \Subscription
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * Generated from protobuf field <code>.Subscription topic = 1;</code>
     * @param \Subscription $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkMessage($var, \Subscription::class);
        $this->topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Message messages = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMessages()
    {
        return $this->messages;
    }

    /**
     * Generated from protobuf field <code>repeated .Message messages = 2;</code>
     * @param \Message[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMessages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Message::class);
        $this->messages = $arr;

        return $this;
    }

}

