<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub.proto

namespace Pubsub;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pubsub.SubscribeRequest</code>
 */
class SubscribeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pubsub.Identity identity = 1;</code>
     */
    private $identity = null;
    /**
     * Generated from protobuf field <code>.pubsub.Subscription subscription = 2;</code>
     */
    private $subscription = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pubsub\Identity $identity
     *     @type \Pubsub\Subscription $subscription
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pubsub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pubsub.Identity identity = 1;</code>
     * @return \Pubsub\Identity
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * Generated from protobuf field <code>.pubsub.Identity identity = 1;</code>
     * @param \Pubsub\Identity $var
     * @return $this
     */
    public function setIdentity($var)
    {
        GPBUtil::checkMessage($var, \Pubsub\Identity::class);
        $this->identity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pubsub.Subscription subscription = 2;</code>
     * @return \Pubsub\Subscription
     */
    public function getSubscription()
    {
        return $this->subscription;
    }

    /**
     * Generated from protobuf field <code>.pubsub.Subscription subscription = 2;</code>
     * @param \Pubsub\Subscription $var
     * @return $this
     */
    public function setSubscription($var)
    {
        GPBUtil::checkMessage($var, \Pubsub\Subscription::class);
        $this->subscription = $var;

        return $this;
    }

}

