<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub/protoc/pubsub.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SubscribeRequest</code>
 */
class SubscribeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Identity identity = 1;</code>
     */
    private $identity = null;
    /**
     * Generated from protobuf field <code>.Subscription subscription = 2;</code>
     */
    private $subscription = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Identity $identity
     *     @type \Subscription $subscription
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pubsub\Protoc\Pubsub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Identity identity = 1;</code>
     * @return \Identity
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * Generated from protobuf field <code>.Identity identity = 1;</code>
     * @param \Identity $var
     * @return $this
     */
    public function setIdentity($var)
    {
        GPBUtil::checkMessage($var, \Identity::class);
        $this->identity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Subscription subscription = 2;</code>
     * @return \Subscription
     */
    public function getSubscription()
    {
        return $this->subscription;
    }

    /**
     * Generated from protobuf field <code>.Subscription subscription = 2;</code>
     * @param \Subscription $var
     * @return $this
     */
    public function setSubscription($var)
    {
        GPBUtil::checkMessage($var, \Subscription::class);
        $this->subscription = $var;

        return $this;
    }

}

